// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package hello

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/tuneinc/truss/deftree/googlethirdparty"

import (
	context "golang.org/x/net/context"
	newcontext "context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Req struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Req) Reset()         { *m = Req{} }
func (m *Req) String() string { return proto.CompactTextString(m) }
func (*Req) ProtoMessage()    {}
func (*Req) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_563c960aed8f3a14, []int{0}
}
func (m *Req) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Req.Unmarshal(m, b)
}
func (m *Req) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Req.Marshal(b, m, deterministic)
}
func (dst *Req) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Req.Merge(dst, src)
}
func (m *Req) XXX_Size() int {
	return xxx_messageInfo_Req.Size(m)
}
func (m *Req) XXX_DiscardUnknown() {
	xxx_messageInfo_Req.DiscardUnknown(m)
}

var xxx_messageInfo_Req proto.InternalMessageInfo

func (m *Req) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Resp struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 string   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Resp) Reset()         { *m = Resp{} }
func (m *Resp) String() string { return proto.CompactTextString(m) }
func (*Resp) ProtoMessage()    {}
func (*Resp) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_563c960aed8f3a14, []int{1}
}
func (m *Resp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Resp.Unmarshal(m, b)
}
func (m *Resp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Resp.Marshal(b, m, deterministic)
}
func (dst *Resp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Resp.Merge(dst, src)
}
func (m *Resp) XXX_Size() int {
	return xxx_messageInfo_Resp.Size(m)
}
func (m *Resp) XXX_DiscardUnknown() {
	xxx_messageInfo_Resp.DiscardUnknown(m)
}

var xxx_messageInfo_Resp proto.InternalMessageInfo

func (m *Resp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Resp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *Resp) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func init() {
	proto.RegisterType((*Req)(nil), "hello.Req")
	proto.RegisterType((*Resp)(nil), "hello.Resp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserClient is the client API for User service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserClient interface {
	GetUsernameV1(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Resp, error)
}

type userClient struct {
	cc *grpc.ClientConn
}

func NewUserClient(cc *grpc.ClientConn) UserClient {
	return &userClient{cc}
}

func (c *userClient) GetUsernameV1(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Resp, error) {
	out := new(Resp)
	err := c.cc.Invoke(ctx, "/hello.User/GetUsernameV1", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServer is the server API for User service.
type UserServer interface {
	GetUsernameV1(newcontext.Context, *Req) (*Resp, error)
}

func RegisterUserServer(s *grpc.Server, srv UserServer) {
	s.RegisterService(&_User_serviceDesc, srv)
}

func _User_GetUsernameV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetUsernameV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hello.User/GetUsernameV1",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetUsernameV1(ctx, req.(*Req))
	}
	return interceptor(ctx, in, info, handler)
}

var _User_serviceDesc = grpc.ServiceDesc{
	ServiceName: "hello.User",
	HandlerType: (*UserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUsernameV1",
			Handler:    _User_GetUsernameV1_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_user_563c960aed8f3a14) }

var fileDescriptor_user_563c960aed8f3a14 = []byte{
	// 225 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0xce, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x80, 0x61, 0xda, 0xb4, 0x82, 0xb3, 0x28, 0x12, 0x10, 0xca, 0x9e, 0x96, 0x9e, 0xf6, 0xd4,
	0xa0, 0xe2, 0x51, 0x10, 0x3c, 0x78, 0x0f, 0xe8, 0x3d, 0xdb, 0x8c, 0x69, 0xa0, 0xcd, 0xb4, 0xc9,
	0xf4, 0xe0, 0xd5, 0x57, 0xf0, 0xd1, 0x7c, 0x05, 0x1f, 0x44, 0x1a, 0x61, 0x6f, 0x1f, 0x33, 0xc3,
	0xf0, 0x03, 0xac, 0x09, 0x63, 0x37, 0x47, 0x62, 0x92, 0xf5, 0x80, 0xe3, 0x48, 0xfb, 0x17, 0xe7,
	0x79, 0x58, 0x4f, 0x5d, 0x4f, 0x93, 0xe2, 0x35, 0xa0, 0x0f, 0xbd, 0xe2, 0xb8, 0xa6, 0xa4, 0x2c,
	0x7e, 0x70, 0x44, 0x54, 0x8e, 0xc8, 0x8d, 0xc8, 0x83, 0x8f, 0x76, 0x36, 0x91, 0x3f, 0x95, 0x09,
	0x81, 0xd8, 0xb0, 0xa7, 0x90, 0xfe, 0x7f, 0xb5, 0xb7, 0x20, 0x34, 0x2e, 0xf2, 0x1a, 0x4a, 0x6f,
	0x9b, 0xe2, 0x50, 0x1c, 0x85, 0x2e, 0xbd, 0x6d, 0x9f, 0xa1, 0xd2, 0x98, 0x66, 0x29, 0xa1, 0xea,
	0xc9, 0x62, 0xde, 0xd4, 0x3a, 0x5b, 0xde, 0x80, 0x98, 0x92, 0x6b, 0xca, 0x43, 0x71, 0xbc, 0xd4,
	0x1b, 0xb7, 0x2b, 0x6b, 0xd8, 0x34, 0x22, 0x8f, 0xb2, 0xef, 0x9f, 0xa0, 0x7a, 0x4b, 0x18, 0xe5,
	0x23, 0x5c, 0xbd, 0x22, 0x6f, 0x0c, 0x66, 0xc2, 0xf7, 0x3b, 0x09, 0x5d, 0xce, 0xef, 0x34, 0x2e,
	0xfb, 0xdd, 0xd9, 0x69, 0x6e, 0x77, 0x5f, 0x3f, 0xbf, 0xdf, 0x65, 0xdd, 0x0a, 0x87, 0x7c, 0xba,
	0xc8, 0x79, 0x0f, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x13, 0xdd, 0xcf, 0xb8, 0xf8, 0x00, 0x00,
	0x00,
}
